language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

before_script:
  - psql -c 'create database cobase_pro;' -U postgres
  - cp conf/application.conf.dist conf/application.conf
  - cp conf/twitter.conf.dist conf/twitter.conf

script: sbt test
