language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

before_script:
  - psql -c 'create database cobase_pro;' -U postgres
  - cp server/conf/application.conf.dist server/conf/application.conf
  - cp server/conf/twitter.conf.dist server/conf/twitter.conf

script: cd server && sbt test
